steps:
  test:
    image: node:20-alpine
    commands:
      - npm ci
      - npm run build
    when:
      - event: [push, pull_request]

  deploy:
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SUPABASE_URL:
        from_secret: supabase_url
      SUPABASE_ANON_KEY:
        from_secret: supabase_anon_key
      OPENAI_API_KEY:
        from_secret: openai_api_key
    commands:
      - pwd
      - ls -la
      - cat docker-compose.yml
      - docker compose down || echo "No running containers"
      - docker compose up -d --build
      - docker image prune -f
    when:
      - event: push
      - branch: main

  notify:
    image: alpine:latest
    commands:
      - echo "✅ ColsenAI Website deployed successfully!"
    when:
      - event: push
      - branch: main
      - status: [success]
