steps:
  test:
    image: node:20-alpine
    commands:
      - npm ci
      - npm run build
    when:
      - event: [push, pull_request]

  deploy:
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      OPENAI_API_KEY:
        from_secret: openai_api_key
      RESEND_API_KEY:
        from_secret: resend_api_key
      FROM_EMAIL:
        from_secret: from_email
      CONTACT_EMAIL:
        from_secret: contact_email
    commands:
      - pwd
      - ls -la
      - cat docker-compose.yml
      - export OPENAI_API_KEY=$OPENAI_API_KEY
      - export RESEND_API_KEY=$resend_api_key
      - export FROM_EMAIL=$from_email
      - export CONTACT_EMAIL=$contact_email
      - docker compose down || echo "No running containers"
      - docker compose up -d --build
      - docker image prune -f
      - echo "Waiting for services to start..."
      - sleep 10
      - echo "Running content ingestion..."
      - docker exec colsenai-website npm run ingest-content
    when:
      - event: push
      - branch: main

  notify:
    image: alpine:latest
    commands:
      - echo "✅ ColsenAI Website deployed successfully!"
    when:
      - event: push
      - branch: main
      - status: [success]
