version: '3.8'

services:
  app-local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: colsenai-website-local
    restart: unless-stopped
    ports:
      - "3001:3001"  # Expose port for local testing
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env  # Load from your local .env file
    networks:
      - local-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  local-network:
    driver: bridge
